---
- name: Apply objects
  shell: "echo '{{ item.stdout }}' | {{ oc }} apply -f - -n {{ item.item.project }}"
  with_items: "{{ hostvars[groups['master'][0]]['imagestreams_export'] }}"
  register: imagestream_apply
- name: tag imagestreams
  command: "{{ oc }} tag {{ item.name }} {{ item.name }}:{{ item.tag.to }}"
  with_items: "{{ imagestreams }}"
#  when: item.tag
