---
- name: List projects
  command: "{{ oc }} projects -q"
  register: existing_projects
- name: Create project
  command: "{{ oc }} new-project {{ item.name }} --display-name='{{ item.display }}' --description='{{ item.description }}' --skip-config-write=true"
  with_items: "{{ projects }}"
  when: item.name not in existing_projects.stdout_lines

- name: List users
  command: "{{ oc }} get users"
  register: existing_users
- name: Create user
  command: "{{ oc }} create user {{ item.name }} --full-name='{{ item.fullname }}'"
  with_items: "{{ users }}"
  ignore_errors: True
# condition not working so we just ignore existing users for now
#  when: "{{ existing_users.stdout_lines }} | search('{{ item.name }}')"
